//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.13 at 12:22:58 PM CET 
//


package org.projekat.zahtev;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="stavka" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded" minOccurs="0">
 *                   &lt;element ref="{http://www.projekat.org/zahtev}lista" minOccurs="0"/>
 *                   &lt;element ref="{http://www.projekat.org/zahtev}drugi_nacin" minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute ref="{http://www.projekat.org/zahtev}id use="required""/>
 *                 &lt;attribute ref="{http://www.projekat.org/zahtev}checked use="required""/>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "stavka"
})
@XmlRootElement(name = "lista")
public class Lista {

    @XmlElement(required = true)
    protected List<Lista.Stavka> stavka;

    /**
     * Gets the value of the stavka property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stavka property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStavka().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Lista.Stavka }
     * 
     * 
     */
    public List<Lista.Stavka> getStavka() {
        if (stavka == null) {
            stavka = new ArrayList<Lista.Stavka>();
        }
        return this.stavka;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded" minOccurs="0">
     *         &lt;element ref="{http://www.projekat.org/zahtev}lista" minOccurs="0"/>
     *         &lt;element ref="{http://www.projekat.org/zahtev}drugi_nacin" minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute ref="{http://www.projekat.org/zahtev}id use="required""/>
     *       &lt;attribute ref="{http://www.projekat.org/zahtev}checked use="required""/>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "content"
    })
    public static class Stavka {

        @XmlElementRefs({
            @XmlElementRef(name = "lista", namespace = "http://www.projekat.org/zahtev", type = Lista.class, required = false),
            @XmlElementRef(name = "drugi_nacin", namespace = "http://www.projekat.org/zahtev", type = JAXBElement.class, required = false)
        })
        @XmlMixed
        protected List<Object> content;
        @XmlAttribute(name = "id", namespace = "http://www.projekat.org/zahtev", required = true)
        protected int id;
        @XmlAttribute(name = "checked", namespace = "http://www.projekat.org/zahtev", required = true)
        protected boolean checked;

        /**
         * Gets the value of the content property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the content property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getContent().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link JAXBElement }{@code <}{@link String }{@code >}
         * {@link String }
         * {@link Lista }
         * 
         * 
         */
        public List<Object> getContent() {
            if (content == null) {
                content = new ArrayList<Object>();
            }
            return this.content;
        }

        /**
         * Gets the value of the id property.
         * 
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the checked property.
         * 
         */
        public boolean isChecked() {
            return checked;
        }

        /**
         * Sets the value of the checked property.
         * 
         */
        public void setChecked(boolean value) {
            this.checked = value;
        }

    }

}
