//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 07:36:55 PM CET 
//


package com.example.demo.klaseZalbaNaOdluku;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Tpodaci_o_zalbi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Tpodaci_o_zalbi">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="naslov">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="podnosilac_zalbe" type="{http://www.ftn.uns.ac.rs/zalbanaodluku}TFizicko_lice"/>
 *         &lt;element name="organ_koji_je_doneo_odluku" type="{http://www.ftn.uns.ac.rs/zalbanaodluku}TPravno_lice"/>
 *         &lt;element name="broj_zalbe" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Tpodaci_o_zalbi", propOrder = {
    "content"
})
public class TpodaciOZalbi {

    @XmlElementRefs({
        @XmlElementRef(name = "naslov", namespace = "http://www.ftn.uns.ac.rs/zalbanaodluku", type = JAXBElement.class),
        @XmlElementRef(name = "datum", namespace = "http://www.ftn.uns.ac.rs/zalbanaodluku", type = JAXBElement.class),
        @XmlElementRef(name = "podnosilac_zalbe", namespace = "http://www.ftn.uns.ac.rs/zalbanaodluku", type = JAXBElement.class),
        @XmlElementRef(name = "organ_koji_je_doneo_odluku", namespace = "http://www.ftn.uns.ac.rs/zalbanaodluku", type = JAXBElement.class),
        @XmlElementRef(name = "broj_zalbe", namespace = "http://www.ftn.uns.ac.rs/zalbanaodluku", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Serializable> content;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link String }
     * {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
     * {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
     * {@link JAXBElement }{@code <}{@link TFizickoLice }{@code >}
     * {@link JAXBElement }{@code <}{@link TPravnoLice }{@code >}
     * 
     * 
     */
    public List<Serializable> getContent() {
        if (content == null) {
            content = new ArrayList<Serializable>();
        }
        return this.content;
    }

}
