//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 09:48:50 PM CET 
//


package com.example.demo.klaseObavestenja;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="opste_informacije" type="{http://www.ftn.uns.ac.rs/obavestenje}Topste_informacije"/>
 *         &lt;element name="naslov">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="podnaslov">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="telo" type="{http://www.ftn.uns.ac.rs/obavestenje}Ttelo_obavestenja"/>
 *         &lt;element name="dostavljeno">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="Imenovanom"/>
 *               &lt;enumeration value="Arhivi"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "opsteInformacije",
    "naslov",
    "podnaslov",
    "telo",
    "dostavljeno"
})
@XmlRootElement(name = "obavestenje")
public class Obavestenje {

    @XmlElement(name = "opste_informacije", required = true)
    protected TopsteInformacije opsteInformacije;
    @XmlElement(required = true)
    protected String naslov;
    @XmlElement(required = true)
    protected String podnaslov;
    @XmlElement(required = true)
    protected TteloObavestenja telo;
    @XmlElement(required = true)
    protected String dostavljeno;

    /**
     * Gets the value of the opsteInformacije property.
     * 
     * @return
     *     possible object is
     *     {@link TopsteInformacije }
     *     
     */
    public TopsteInformacije getOpsteInformacije() {
        return opsteInformacije;
    }

    /**
     * Sets the value of the opsteInformacije property.
     * 
     * @param value
     *     allowed object is
     *     {@link TopsteInformacije }
     *     
     */
    public void setOpsteInformacije(TopsteInformacije value) {
        this.opsteInformacije = value;
    }

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslov() {
        return naslov;
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the podnaslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPodnaslov() {
        return podnaslov;
    }

    /**
     * Sets the value of the podnaslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPodnaslov(String value) {
        this.podnaslov = value;
    }

    /**
     * Gets the value of the telo property.
     * 
     * @return
     *     possible object is
     *     {@link TteloObavestenja }
     *     
     */
    public TteloObavestenja getTelo() {
        return telo;
    }

    /**
     * Sets the value of the telo property.
     * 
     * @param value
     *     allowed object is
     *     {@link TteloObavestenja }
     *     
     */
    public void setTelo(TteloObavestenja value) {
        this.telo = value;
    }

    /**
     * Gets the value of the dostavljeno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDostavljeno() {
        return dostavljeno;
    }

    /**
     * Sets the value of the dostavljeno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDostavljeno(String value) {
        this.dostavljeno = value;
    }

}
