//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.30 at 04:19:07 PM CET 
//


package com.example.demo.klaseObavestenja;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demo.klase package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demo.klase
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Obavestenje }
     * 
     */
    public Obavestenje createObavestenje() {
        return new Obavestenje();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo }
     * 
     */
    public Obavestenje.Telo createObavestenjeTelo() {
        return new Obavestenje.Telo();
    }

    /**
     * Create an instance of {@link Obavestenje.OpsteInformacije }
     * 
     */
    public Obavestenje.OpsteInformacije createObavestenjeOpsteInformacije() {
        return new Obavestenje.OpsteInformacije();
    }

    /**
     * Create an instance of {@link Obavestenje.OpsteInformacije.PodaciOPodnosiocu }
     * 
     */
    public Obavestenje.OpsteInformacije.PodaciOPodnosiocu createObavestenjeOpsteInformacijePodaciOPodnosiocu() {
        return new Obavestenje.OpsteInformacije.PodaciOPodnosiocu();
    }

    /**
     * Create an instance of {@link Datum }
     * 
     */
    public Datum createDatum() {
        return new Datum();
    }

    /**
     * Create an instance of {@link Obavestenje.Telo.AdresaOrgana }
     * 
     */
    public Obavestenje.Telo.AdresaOrgana createObavestenjeTeloAdresaOrgana() {
        return new Obavestenje.Telo.AdresaOrgana();
    }

    /**
     * Create an instance of {@link Obavestenje.OpsteInformacije.PodaciOOrganu }
     * 
     */
    public Obavestenje.OpsteInformacije.PodaciOOrganu createObavestenjeOpsteInformacijePodaciOOrganu() {
        return new Obavestenje.OpsteInformacije.PodaciOOrganu();
    }

    /**
     * Create an instance of {@link Obavestenje.OpsteInformacije.PodaciOPodnosiocu.Adresa }
     * 
     */
    public Obavestenje.OpsteInformacije.PodaciOPodnosiocu.Adresa createObavestenjeOpsteInformacijePodaciOPodnosiocuAdresa() {
        return new Obavestenje.OpsteInformacije.PodaciOPodnosiocu.Adresa();
    }

}
