//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 09:48:50 PM CET 
//


package com.example.demo.klaseObavestenja;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.example.demo.klaseObavestenja package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.example.demo.klaseObavestenja
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Obavestenje }
     * 
     */
    public Obavestenje createObavestenje() {
        return new Obavestenje();
    }

    /**
     * Create an instance of {@link TopsteInformacije }
     * 
     */
    public TopsteInformacije createTopsteInformacije() {
        return new TopsteInformacije();
    }

    /**
     * Create an instance of {@link TteloObavestenja }
     * 
     */
    public TteloObavestenja createTteloObavestenja() {
        return new TteloObavestenja();
    }

    /**
     * Create an instance of {@link Torgan }
     * 
     */
    public Torgan createTorgan() {
        return new Torgan();
    }

    /**
     * Create an instance of {@link TadresaOrgana }
     * 
     */
    public TadresaOrgana createTadresaOrgana() {
        return new TadresaOrgana();
    }

    /**
     * Create an instance of {@link Tdatum }
     * 
     */
    public Tdatum createTdatum() {
        return new Tdatum();
    }

    /**
     * Create an instance of {@link Tpodnosilac }
     * 
     */
    public Tpodnosilac createTpodnosilac() {
        return new Tpodnosilac();
    }

    /**
     * Create an instance of {@link TadresaPodnosioca }
     * 
     */
    public TadresaPodnosioca createTadresaPodnosioca() {
        return new TadresaPodnosioca();
    }

}
