//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.07 at 09:48:50 PM CET 
//


package com.example.demo.klaseObavestenja;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Topste_informacije complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Topste_informacije">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="podaci_o_organu" type="{http://www.ftn.uns.ac.rs/obavestenje}Torgan"/>
 *         &lt;element name="broj_predmeta">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="datum" type="{http://www.ftn.uns.ac.rs/obavestenje}Tdatum"/>
 *         &lt;element name="podaci_o_podnosiocu" type="{http://www.ftn.uns.ac.rs/obavestenje}Tpodnosilac"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Topste_informacije", propOrder = {
    "podaciOOrganu",
    "brojPredmeta",
    "datum",
    "podaciOPodnosiocu"
})
public class TopsteInformacije {

    @XmlElement(name = "podaci_o_organu", required = true)
    protected Torgan podaciOOrganu;
    @XmlElement(name = "broj_predmeta", required = true)
    protected String brojPredmeta;
    @XmlElement(required = true)
    protected Tdatum datum;
    @XmlElement(name = "podaci_o_podnosiocu", required = true)
    protected Tpodnosilac podaciOPodnosiocu;

    /**
     * Gets the value of the podaciOOrganu property.
     * 
     * @return
     *     possible object is
     *     {@link Torgan }
     *     
     */
    public Torgan getPodaciOOrganu() {
        return podaciOOrganu;
    }

    /**
     * Sets the value of the podaciOOrganu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Torgan }
     *     
     */
    public void setPodaciOOrganu(Torgan value) {
        this.podaciOOrganu = value;
    }

    /**
     * Gets the value of the brojPredmeta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBrojPredmeta() {
        return brojPredmeta;
    }

    /**
     * Sets the value of the brojPredmeta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBrojPredmeta(String value) {
        this.brojPredmeta = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link Tdatum }
     *     
     */
    public Tdatum getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tdatum }
     *     
     */
    public void setDatum(Tdatum value) {
        this.datum = value;
    }

    /**
     * Gets the value of the podaciOPodnosiocu property.
     * 
     * @return
     *     possible object is
     *     {@link Tpodnosilac }
     *     
     */
    public Tpodnosilac getPodaciOPodnosiocu() {
        return podaciOPodnosiocu;
    }

    /**
     * Sets the value of the podaciOPodnosiocu property.
     * 
     * @param value
     *     allowed object is
     *     {@link Tpodnosilac }
     *     
     */
    public void setPodaciOPodnosiocu(Tpodnosilac value) {
        this.podaciOPodnosiocu = value;
    }

}
