//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.31 at 06:25:33 PM CET 
//


package com.xml.project.model.reportListItem;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="reportItem">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="zahtevBrojPodnetih" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="zahtevBrojUsvojenih" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="zahtevBrojOdbacenih" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="zahtevBrojOdbijenih" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="zalbaBrojPodnetih" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="zalbaBrojZbogNepostupanja" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="zalbaBrojZbogOdbijanja" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "reportItem"
})
@XmlRootElement(name = "reportListResponse")
public class ReportListResponse {

    @XmlElement(required = true)
    protected List<ReportListResponse.ReportItem> reportItem;

    /**
     * Gets the value of the reportItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reportItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReportItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReportListResponse.ReportItem }
     * 
     * 
     */
    
    public List<ReportListResponse.ReportItem> getReportItem() {
        if (reportItem == null) {
            reportItem = new ArrayList<ReportListResponse.ReportItem>();
        }
        return this.reportItem;
    }


    @Override
	public String toString() {
    	StringBuilder sb = new StringBuilder();
    	for(ReportListResponse.ReportItem item : reportItem) {
    		sb.append("item = " + item + " \n");
    	}
		return "ReportListResponse [reportItem=" + sb.toString() + "]";
	}


	public void setReportItem(List<ReportListResponse.ReportItem> reportItem) {
		this.reportItem = reportItem;
	}


	/**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="zahtevBrojPodnetih" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="zahtevBrojUsvojenih" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="zahtevBrojOdbacenih" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="zahtevBrojOdbijenih" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="zalbaBrojPodnetih" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="zalbaBrojZbogNepostupanja" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="zalbaBrojZbogOdbijanja" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "datum",
        "zahtevBrojPodnetih",
        "zahtevBrojUsvojenih",
        "zahtevBrojOdbacenih",
        "zahtevBrojOdbijenih",
        "zalbaBrojPodnetih",
        "zalbaBrojZbogNepostupanja",
        "zalbaBrojZbogOdbijanja"
    })
    public static class ReportItem {

        @XmlElement(required = true)
        protected String id;
        @XmlElement(required = true)
        protected String datum;
        protected int zahtevBrojPodnetih;
        protected int zahtevBrojUsvojenih;
        protected int zahtevBrojOdbacenih;
        protected int zahtevBrojOdbijenih;
        protected int zalbaBrojPodnetih;
        protected int zalbaBrojZbogNepostupanja;
        protected int zalbaBrojZbogOdbijanja;

        
        @Override
		public String toString() {
			return "ReportItem [id=" + id + ", datum=" + datum + ", zahtevBrojPodnetih=" + zahtevBrojPodnetih
					+ ", zahtevBrojUsvojenih=" + zahtevBrojUsvojenih + ", zahtevBrojOdbacenih=" + zahtevBrojOdbacenih
					+ ", zahtevBrojOdbijenih=" + zahtevBrojOdbijenih + ", zalbaBrojPodnetih=" + zalbaBrojPodnetih
					+ ", zalbaBrojZbogNepostupanja=" + zalbaBrojZbogNepostupanja + ", zalbaBrojZbogOdbijanja="
					+ zalbaBrojZbogOdbijanja + "]";
		}

		/**
         * Gets the value of the id property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setId(String value) {
            this.id = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatum(String value) {
            this.datum = value;
        }

        /**
         * Gets the value of the zahtevBrojPodnetih property.
         * 
         */
        public int getZahtevBrojPodnetih() {
            return zahtevBrojPodnetih;
        }

        /**
         * Sets the value of the zahtevBrojPodnetih property.
         * 
         */
        public void setZahtevBrojPodnetih(int value) {
            this.zahtevBrojPodnetih = value;
        }

        /**
         * Gets the value of the zahtevBrojUsvojenih property.
         * 
         */
        public int getZahtevBrojUsvojenih() {
            return zahtevBrojUsvojenih;
        }

        /**
         * Sets the value of the zahtevBrojUsvojenih property.
         * 
         */
        public void setZahtevBrojUsvojenih(int value) {
            this.zahtevBrojUsvojenih = value;
        }

        /**
         * Gets the value of the zahtevBrojOdbacenih property.
         * 
         */
        public int getZahtevBrojOdbacenih() {
            return zahtevBrojOdbacenih;
        }

        /**
         * Sets the value of the zahtevBrojOdbacenih property.
         * 
         */
        public void setZahtevBrojOdbacenih(int value) {
            this.zahtevBrojOdbacenih = value;
        }

        /**
         * Gets the value of the zahtevBrojOdbijenih property.
         * 
         */
        public int getZahtevBrojOdbijenih() {
            return zahtevBrojOdbijenih;
        }

        /**
         * Sets the value of the zahtevBrojOdbijenih property.
         * 
         */
        public void setZahtevBrojOdbijenih(int value) {
            this.zahtevBrojOdbijenih = value;
        }

        /**
         * Gets the value of the zalbaBrojPodnetih property.
         * 
         */
        public int getZalbaBrojPodnetih() {
            return zalbaBrojPodnetih;
        }

        /**
         * Sets the value of the zalbaBrojPodnetih property.
         * 
         */
        public void setZalbaBrojPodnetih(int value) {
            this.zalbaBrojPodnetih = value;
        }

        /**
         * Gets the value of the zalbaBrojZbogNepostupanja property.
         * 
         */
        public int getZalbaBrojZbogNepostupanja() {
            return zalbaBrojZbogNepostupanja;
        }

        /**
         * Sets the value of the zalbaBrojZbogNepostupanja property.
         * 
         */
        public void setZalbaBrojZbogNepostupanja(int value) {
            this.zalbaBrojZbogNepostupanja = value;
        }

        /**
         * Gets the value of the zalbaBrojZbogOdbijanja property.
         * 
         */
        public int getZalbaBrojZbogOdbijanja() {
            return zalbaBrojZbogOdbijanja;
        }

        /**
         * Sets the value of the zalbaBrojZbogOdbijanja property.
         * 
         */
        public void setZalbaBrojZbogOdbijanja(int value) {
            this.zalbaBrojZbogOdbijanja = value;
        }

    }

}
