package com.spring.soap.ws.hello;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T14:56:21.149+01:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "PoverenikService", 
                  wsdlLocation = "classpath:wsdl/Poverenik.wsdl",
                  targetNamespace = "http://soap.spring.com/ws/poverenik") 
public class PoverenikService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.spring.com/ws/poverenik", "PoverenikService");
    public final static QName PoverenikPort = new QName("http://soap.spring.com/ws/poverenik", "PoverenikPort");
    static {
        URL url = PoverenikService.class.getClassLoader().getResource("wsdl/Poverenik.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(PoverenikService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:wsdl/Poverenik.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public PoverenikService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PoverenikService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PoverenikService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public PoverenikService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public PoverenikService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public PoverenikService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Poverenik
     */
    @WebEndpoint(name = "PoverenikPort")
    public Poverenik getPoverenikPort() {
        return super.getPort(PoverenikPort, Poverenik.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Poverenik
     */
    @WebEndpoint(name = "PoverenikPort")
    public Poverenik getPoverenikPort(WebServiceFeature... features) {
        return super.getPort(PoverenikPort, Poverenik.class, features);
    }

}
