
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.spring.soap.ws.hello;

import java.io.IOException;

import javax.xml.parsers.ParserConfigurationException;
import javax.xml.transform.TransformerException;

import org.xml.sax.SAXException;
import org.xmldb.api.base.XMLDBException;

import com.xml.project.service.DecisionAppealService;
import com.xml.project.service.ExplanationService;
import com.xml.project.service.SilenceAppealService;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2020-12-26T14:56:21.123+01:00
 * Generated source version: 3.2.1
 * 
 */

@javax.jws.WebService(
                      serviceName = "PoverenikService",
                      portName = "PoverenikPort",
                      targetNamespace = "http://soap.spring.com/ws/poverenik",
                     // wsdlLocation = "classpath:wsdl/Poverenik.wsdl",
                      endpointInterface = "com.spring.soap.ws.hello.Poverenik")
public class PoverenikPortImpl implements Poverenik {

    /*DecisionAppealService dService;
    SilenceAppealService sService;*/
    ExplanationService service;
    
	public PoverenikPortImpl() {
		service = new ExplanationService();
		//sService = new SilenceAppealService();
	}
	
	@Override
    public String sayHi(String text) { 
        System.out.println(text);
        try {
        	System.out.println("Inovked sayHi method");
            return "Poverenik " + text;
          
        } catch (Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

	@Override
	public String saveExplanation(String xml) {
		System.out.println("saveExplanation in soap");
		try {
			service.save(xml);
			return "ok";
		} catch (ClassNotFoundException | InstantiationException | IllegalAccessException | ParserConfigurationException
				| SAXException | IOException | TransformerException | XMLDBException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
			return "error";
		}
	}
	
}
