SELECT * FROM <http://localhost:8081/fuseki/Project/data/decisionAppealMetadata> WHERE {
  ?organVlasti <http://www.projekat.org/zalbanaodluku/predicate/organVlasti> ?organVlasti .
  ?broj <http://www.projekat.org/zalbanaodluku/predicate/broj> ?broj .
  ?ime <http://www.projekat.org/zalbanaodluku/predicate/ime> ?ime .
  ?prezime <http://www.projekat.org/zalbanaodluku/predicate/prezime> ?prezime .
  ?mesto <http://www.projekat.org/zalbanaodluku/predicate/mesto> ?mesto .
  ?datum <http://www.projekat.org/zalbanaodluku/predicate/datum> ?datum .
  FILTER( CONTAINS(UCASE(str(?organVlasti)), UCASE("{{organVlasti}}"))
    && CONTAINS(UCASE(str(?broj)), UCASE("{{broj}}"))
    && CONTAINS(UCASE(str(?ime)), UCASE("{{ime}}"))
    && CONTAINS(UCASE(str(?prezime)), UCASE("{{prezime}}"))
    && CONTAINS(UCASE(str(?mesto)), UCASE("{{mesto}}"))
    && CONTAINS(UCASE(str(?datum)), UCASE("{{datum}}"))
  ) .
} 
