SELECT * FROM <http://localhost:8081/fuseki/Project/data/requestMetadata> WHERE {
	?ime <http://www.ftn.uns.ac.rs/obavestenje/predicate/ime> ?ime .
	?prezime <http://www.ftn.uns.ac.rs/obavestenje/predicate/prezime> ?prezime .
	?datum <http://www.ftn.uns.ac.rs/obavestenje/predicate/datum> ?datum .
	?broj_predmeta <<http://www.ftn.uns.ac.rs/obavestenje/predicate/brojPredmeta> ?broj_predmeta .
	FILTER( CONTAINS(UCASE(str(?ime)), UCASE("{{ime}}"))
    && CONTAINS(UCASE(str(?prezime)), UCASE("{{prezime}}"))
    && CONTAINS(UCASE(str(?datum)), UCASE("{{datum}}"))
    && CONTAINS(UCASE(str(?broj_predmeta)), UCASE("{{broj_predmeta}}"))
  ) .
}