SELECT * FROM <http://localhost:8081/fuseki/Project/data/responseMetadata> WHERE {
  ?resenje <http://www.projekat.org/predicate/broj> ?broj .
  ?resenje <http://www.projekat.org/predicate/status> ?status .
  ?resenje <http://www.projekat.org/predicate/datum> ?datum .
  FILTER( CONTAINS(UCASE(str(?broj)), UCASE("{{broj}}"))
    || CONTAINS(UCASE(str(?status)), UCASE("{{status}}"))
    || CONTAINS(UCASE(str(?datum)), UCASE("{{datum}}"))
  ) .
} 
