SELECT * FROM <http://localhost:8081/fuseki/OrganVlasti/data/responseMetadata> WHERE {
  ?broj <http://www.projekat.org/resenje/predicate/broj> ?broj .
  ?status <http://www.projekat.org/resenje/predicate/status> ?status .
  ?osobaIme <http://www.projekat.org/resenje/predicate/osobaIme> ?osobaIme .
  ?osobaPrezime <http://www.projekat.org/resenje/predicate/osobaPrezime> ?osobaPrezime .
  ?institucijaNaziv <http://www.projekat.org/resenje/predicate/institucijaNaziv> ?institucijaNaziv .
  ?datum <http://www.projekat.org/resenje/predicate/datum> ?datum .
  ?trazena_informacija <http://www.projekat.org/resenje/predicate/trazena_informacija> ?trazena_informacija .
  ?poverenikIme <http://www.projekat.org/resenje/predicate/poverenikIme> ?poverenikIme .
  ?poverenikPrezime <http://www.projekat.org/resenje/predicate/poverenikPrezime> ?poverenikPrezime .
  FILTER( CONTAINS(UCASE(str(?broj)), UCASE("{{broj}}"))
    && CONTAINS(UCASE(str(?status)), UCASE("{{status}}"))
    && CONTAINS(UCASE(str(?osobaIme)), UCASE("{{osobaIme}}"))
    && CONTAINS(UCASE(str(?osobaPrezime)), UCASE("{{osobaPrezime}}"))
    && CONTAINS(UCASE(str(?institucijaNaziv)), UCASE("{{institucijaNaziv}}"))
    && CONTAINS(UCASE(str(?datum)), UCASE("{{datum}}"))
    && CONTAINS(UCASE(str(?trazena_informacija)), UCASE("{{trazena_informacija}}"))
    && CONTAINS(UCASE(str(?poverenikIme)), UCASE("{{poverenikIme}}"))
    && CONTAINS(UCASE(str(?poverenikPrezime)), UCASE("{{poverenikPrezime}}"))
  ) .
} 
