//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.19 at 10:24:15 PM CET 
//


package org.projekat.zalbanaodluku;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.projekat.zalbanaodluku package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _TpodaciOZalbiOrganKojiJeDoneoOdluku_QNAME = new QName("http://www.projekat.org/zalbanaodluku", "organ_koji_je_doneo_odluku");
    private final static QName _TpodaciOZalbiNaslov_QNAME = new QName("http://www.projekat.org/zalbanaodluku", "naslov");
    private final static QName _TpodaciOZalbiDatum_QNAME = new QName("http://www.projekat.org/zalbanaodluku", "datum");
    private final static QName _TpodaciOZalbiBrojZalbe_QNAME = new QName("http://www.projekat.org/zalbanaodluku", "broj_zalbe");
    private final static QName _TpodaciOZalbiPodnosilacZalbe_QNAME = new QName("http://www.projekat.org/zalbanaodluku", "podnosilac_zalbe");
    private final static QName _TsadrzajZalbeZbogCegaSePobijaOdluka_QNAME = new QName("http://www.projekat.org/zalbanaodluku", "zbog_cega_se_pobija_odluka");
    private final static QName _TsadrzajZalbePredlogPovereniku_QNAME = new QName("http://www.projekat.org/zalbanaodluku", "predlog_povereniku");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.projekat.zalbanaodluku
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku }
     * 
     */
    public ZalbaNaOdluku createZalbaNaOdluku() {
        return new ZalbaNaOdluku();
    }

    /**
     * Create an instance of {@link TmestoDatum }
     * 
     */
    public TmestoDatum createTmestoDatum() {
        return new TmestoDatum();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TpodaciOZalbi }
     * 
     */
    public TpodaciOZalbi createTpodaciOZalbi() {
        return new TpodaciOZalbi();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link ZalbaNaOdluku.ZalbaStatus }
     * 
     */
    public ZalbaNaOdluku.ZalbaStatus createZalbaNaOdlukuZalbaStatus() {
        return new ZalbaNaOdluku.ZalbaStatus();
    }

    /**
     * Create an instance of {@link TsadrzajZalbe }
     * 
     */
    public TsadrzajZalbe createTsadrzajZalbe() {
        return new TsadrzajZalbe();
    }

    /**
     * Create an instance of {@link Tnapomena }
     * 
     */
    public Tnapomena createTnapomena() {
        return new Tnapomena();
    }

    /**
     * Create an instance of {@link TmestoDatum.Mesto }
     * 
     */
    public TmestoDatum.Mesto createTmestoDatumMesto() {
        return new TmestoDatum.Mesto();
    }

    /**
     * Create an instance of {@link TmestoDatum.Datum }
     * 
     */
    public TmestoDatum.Datum createTmestoDatumDatum() {
        return new TmestoDatum.Datum();
    }

    /**
     * Create an instance of {@link TFizickoLice.Ime }
     * 
     */
    public TFizickoLice.Ime createTFizickoLiceIme() {
        return new TFizickoLice.Ime();
    }

    /**
     * Create an instance of {@link TFizickoLice.Prezime }
     * 
     */
    public TFizickoLice.Prezime createTFizickoLicePrezime() {
        return new TFizickoLice.Prezime();
    }

    /**
     * Create an instance of {@link TpodaciOZalbi.OrganKojiJeDoneoOdluku }
     * 
     */
    public TpodaciOZalbi.OrganKojiJeDoneoOdluku createTpodaciOZalbiOrganKojiJeDoneoOdluku() {
        return new TpodaciOZalbi.OrganKojiJeDoneoOdluku();
    }

    /**
     * Create an instance of {@link TpodaciOZalbi.BrojZalbe }
     * 
     */
    public TpodaciOZalbi.BrojZalbe createTpodaciOZalbiBrojZalbe() {
        return new TpodaciOZalbi.BrojZalbe();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TpodaciOZalbi.OrganKojiJeDoneoOdluku }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.projekat.org/zalbanaodluku", name = "organ_koji_je_doneo_odluku", scope = TpodaciOZalbi.class)
    public JAXBElement<TpodaciOZalbi.OrganKojiJeDoneoOdluku> createTpodaciOZalbiOrganKojiJeDoneoOdluku(TpodaciOZalbi.OrganKojiJeDoneoOdluku value) {
        return new JAXBElement<TpodaciOZalbi.OrganKojiJeDoneoOdluku>(_TpodaciOZalbiOrganKojiJeDoneoOdluku_QNAME, TpodaciOZalbi.OrganKojiJeDoneoOdluku.class, TpodaciOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.projekat.org/zalbanaodluku", name = "naslov", scope = TpodaciOZalbi.class)
    public JAXBElement<String> createTpodaciOZalbiNaslov(String value) {
        return new JAXBElement<String>(_TpodaciOZalbiNaslov_QNAME, String.class, TpodaciOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.projekat.org/zalbanaodluku", name = "datum", scope = TpodaciOZalbi.class)
    public JAXBElement<String> createTpodaciOZalbiDatum(String value) {
        return new JAXBElement<String>(_TpodaciOZalbiDatum_QNAME, String.class, TpodaciOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TpodaciOZalbi.BrojZalbe }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.projekat.org/zalbanaodluku", name = "broj_zalbe", scope = TpodaciOZalbi.class)
    public JAXBElement<TpodaciOZalbi.BrojZalbe> createTpodaciOZalbiBrojZalbe(TpodaciOZalbi.BrojZalbe value) {
        return new JAXBElement<TpodaciOZalbi.BrojZalbe>(_TpodaciOZalbiBrojZalbe_QNAME, TpodaciOZalbi.BrojZalbe.class, TpodaciOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TFizickoLice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.projekat.org/zalbanaodluku", name = "podnosilac_zalbe", scope = TpodaciOZalbi.class)
    public JAXBElement<TFizickoLice> createTpodaciOZalbiPodnosilacZalbe(TFizickoLice value) {
        return new JAXBElement<TFizickoLice>(_TpodaciOZalbiPodnosilacZalbe_QNAME, TFizickoLice.class, TpodaciOZalbi.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.projekat.org/zalbanaodluku", name = "zbog_cega_se_pobija_odluka", scope = TsadrzajZalbe.class)
    public JAXBElement<String> createTsadrzajZalbeZbogCegaSePobijaOdluka(String value) {
        return new JAXBElement<String>(_TsadrzajZalbeZbogCegaSePobijaOdluka_QNAME, String.class, TsadrzajZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.projekat.org/zalbanaodluku", name = "datum", scope = TsadrzajZalbe.class)
    public JAXBElement<String> createTsadrzajZalbeDatum(String value) {
        return new JAXBElement<String>(_TpodaciOZalbiDatum_QNAME, String.class, TsadrzajZalbe.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.projekat.org/zalbanaodluku", name = "predlog_povereniku", scope = TsadrzajZalbe.class)
    public JAXBElement<String> createTsadrzajZalbePredlogPovereniku(String value) {
        return new JAXBElement<String>(_TsadrzajZalbePredlogPovereniku_QNAME, String.class, TsadrzajZalbe.class, value);
    }

}
