//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.17 at 03:59:33 PM CET 
//


package com.xml.project.model.noticeResponse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="noticeItem">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="organVlastiUsername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="nazivOrgana" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="sedisteOrgana" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="imePodnosioca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="prezimePodnosioca" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="iznos" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "noticeItem"
})
@XmlRootElement(name = "noticeListResponse")
public class NoticeListResponse {

    @XmlElement(required = true)
    protected List<NoticeListResponse.NoticeItem> noticeItem;

    /**
     * Gets the value of the noticeItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noticeItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoticeItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoticeListResponse.NoticeItem }
     * 
     * 
     */
    public List<NoticeListResponse.NoticeItem> getNoticeItem() {
        if (noticeItem == null) {
            noticeItem = new ArrayList<NoticeListResponse.NoticeItem>();
        }
        return this.noticeItem;
    }


    public void setNoticeItem(List<NoticeListResponse.NoticeItem> noticeItem) {
		this.noticeItem = noticeItem;
	}

    

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		for(NoticeListResponse.NoticeItem i : noticeItem) {
			sb.append("notice = " + i);
		}
		return "NoticeListResponse = " + sb.toString();
	}



	/**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="username" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="organVlastiUsername" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="nazivOrgana" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="sedisteOrgana" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="imePodnosioca" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="prezimePodnosioca" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="iznos" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "broj",
        "username",
        "datum",
        "organVlastiUsername",
        "nazivOrgana",
        "sedisteOrgana",
        "imePodnosioca",
        "prezimePodnosioca",
        "iznos"
    })
    public static class NoticeItem {

        @XmlElement(required = true)
        protected String broj;
        @XmlElement(required = true)
        protected String username;
        @XmlElement(required = true)
        protected String datum;
        @XmlElement(required = true)
        protected String organVlastiUsername;
        @XmlElement(required = true)
        protected String nazivOrgana;
        @XmlElement(required = true)
        protected String sedisteOrgana;
        @XmlElement(required = true)
        protected String imePodnosioca;
        @XmlElement(required = true)
        protected String prezimePodnosioca;
        @XmlElement(required = true)
        protected String iznos;

        
        @Override
		public String toString() {
			return "NoticeItem [broj=" + broj + ", username=" + username + ", datum=" + datum + ", organVlastiUsername="
					+ organVlastiUsername + ", nazivOrgana=" + nazivOrgana + ", sedisteOrgana=" + sedisteOrgana
					+ ", imePodnosioca=" + imePodnosioca + ", prezimePodnosioca=" + prezimePodnosioca + ", iznos="
					+ iznos + "]";
		}

		/**
         * Gets the value of the broj property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBroj() {
            return broj;
        }

        /**
         * Sets the value of the broj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBroj(String value) {
            this.broj = value;
        }

        /**
         * Gets the value of the username property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getUsername() {
            return username;
        }

        /**
         * Sets the value of the username property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setUsername(String value) {
            this.username = value;
        }

        /**
         * Gets the value of the datum property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatum() {
            return datum;
        }

        /**
         * Sets the value of the datum property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatum(String value) {
            this.datum = value;
        }

        /**
         * Gets the value of the organVlastiUsername property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrganVlastiUsername() {
            return organVlastiUsername;
        }

        /**
         * Sets the value of the organVlastiUsername property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrganVlastiUsername(String value) {
            this.organVlastiUsername = value;
        }

        /**
         * Gets the value of the nazivOrgana property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNazivOrgana() {
            return nazivOrgana;
        }

        /**
         * Sets the value of the nazivOrgana property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNazivOrgana(String value) {
            this.nazivOrgana = value;
        }

        /**
         * Gets the value of the sedisteOrgana property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSedisteOrgana() {
            return sedisteOrgana;
        }

        /**
         * Sets the value of the sedisteOrgana property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSedisteOrgana(String value) {
            this.sedisteOrgana = value;
        }

        /**
         * Gets the value of the imePodnosioca property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getImePodnosioca() {
            return imePodnosioca;
        }

        /**
         * Sets the value of the imePodnosioca property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setImePodnosioca(String value) {
            this.imePodnosioca = value;
        }

        /**
         * Gets the value of the prezimePodnosioca property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPrezimePodnosioca() {
            return prezimePodnosioca;
        }

        /**
         * Sets the value of the prezimePodnosioca property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPrezimePodnosioca(String value) {
            this.prezimePodnosioca = value;
        }

        /**
         * Gets the value of the iznos property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIznos() {
            return iznos;
        }

        /**
         * Sets the value of the iznos property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIznos(String value) {
            this.iznos = value;
        }

    }

}
