//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.20 at 01:21:39 PM CET 
//


package com.xml.project.model.silenceAppealResponse;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element name="SAppealItem">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="podnosiocUlica" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="podnosiocGrad" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="podnosiocIme" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="podnosiocPrezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="podnosiocUsername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="organVlasti" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="mestoSlanja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="datumSlanja" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="poverenikUsername" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="razlog" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "sAppealItem"
})
@XmlRootElement(name = "SAppealListResponse")
public class SAppealListResponse {

    @XmlElement(name = "SAppealItem", required = true)
    protected List<SAppealListResponse.SAppealItem> sAppealItem;

    /**
     * Gets the value of the sAppealItem property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the sAppealItem property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSAppealItem().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SAppealListResponse.SAppealItem }
     * 
     * 
     */
    public List<SAppealListResponse.SAppealItem> getSAppealItem() {
        if (sAppealItem == null) {
            sAppealItem = new ArrayList<SAppealListResponse.SAppealItem>();
        }
        return this.sAppealItem;
    }


    public void setsAppealItem(List<SAppealListResponse.SAppealItem> sAppealItem) {
		this.sAppealItem = sAppealItem;
	}


	/**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="status" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="podnosiocUlica" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="podnosiocGrad" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="podnosiocIme" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="podnosiocPrezime" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="podnosiocUsername" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="organVlasti" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="broj" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="mestoSlanja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="datumSlanja" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="poverenikUsername" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="razlog" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "status",
        "podnosiocUlica",
        "podnosiocGrad",
        "podnosiocIme",
        "podnosiocPrezime",
        "podnosiocUsername",
        "organVlasti",
        "broj",
        "mestoSlanja",
        "datumSlanja",
        "poverenikUsername",
        "razlog"
    })
    public static class SAppealItem {

        @XmlElement(required = true)
        protected String status;
        @XmlElement(required = true)
        protected String podnosiocUlica;
        @XmlElement(required = true)
        protected String podnosiocGrad;
        @XmlElement(required = true)
        protected String podnosiocIme;
        @XmlElement(required = true)
        protected String podnosiocPrezime;
        @XmlElement(required = true)
        protected String podnosiocUsername;
        @XmlElement(required = true)
        protected String organVlasti;
        @XmlElement(required = true)
        protected String broj;
        @XmlElement(required = true)
        protected String mestoSlanja;
        @XmlElement(required = true)
        protected String datumSlanja;
        @XmlElement(required = true)
        protected String poverenikUsername;
        @XmlElement(required = true)
        protected String razlog;

        /**
         * Gets the value of the status property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStatus() {
            return status;
        }

        /**
         * Sets the value of the status property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStatus(String value) {
            this.status = value;
        }

        /**
         * Gets the value of the podnosiocUlica property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPodnosiocUlica() {
            return podnosiocUlica;
        }

        /**
         * Sets the value of the podnosiocUlica property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPodnosiocUlica(String value) {
            this.podnosiocUlica = value;
        }

        /**
         * Gets the value of the podnosiocGrad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPodnosiocGrad() {
            return podnosiocGrad;
        }

        /**
         * Sets the value of the podnosiocGrad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPodnosiocGrad(String value) {
            this.podnosiocGrad = value;
        }

        /**
         * Gets the value of the podnosiocIme property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPodnosiocIme() {
            return podnosiocIme;
        }

        /**
         * Sets the value of the podnosiocIme property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPodnosiocIme(String value) {
            this.podnosiocIme = value;
        }

        /**
         * Gets the value of the podnosiocPrezime property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPodnosiocPrezime() {
            return podnosiocPrezime;
        }

        /**
         * Sets the value of the podnosiocPrezime property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPodnosiocPrezime(String value) {
            this.podnosiocPrezime = value;
        }

        /**
         * Gets the value of the podnosiocUsername property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPodnosiocUsername() {
            return podnosiocUsername;
        }

        /**
         * Sets the value of the podnosiocUsername property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPodnosiocUsername(String value) {
            this.podnosiocUsername = value;
        }

        /**
         * Gets the value of the organVlasti property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOrganVlasti() {
            return organVlasti;
        }

        /**
         * Sets the value of the organVlasti property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOrganVlasti(String value) {
            this.organVlasti = value;
        }

        /**
         * Gets the value of the broj property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBroj() {
            return broj;
        }

        /**
         * Sets the value of the broj property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBroj(String value) {
            this.broj = value;
        }

        /**
         * Gets the value of the mestoSlanja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMestoSlanja() {
            return mestoSlanja;
        }

        /**
         * Sets the value of the mestoSlanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMestoSlanja(String value) {
            this.mestoSlanja = value;
        }

        /**
         * Gets the value of the datumSlanja property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDatumSlanja() {
            return datumSlanja;
        }

        /**
         * Sets the value of the datumSlanja property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDatumSlanja(String value) {
            this.datumSlanja = value;
        }

        /**
         * Gets the value of the poverenikUsername property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPoverenikUsername() {
            return poverenikUsername;
        }

        /**
         * Sets the value of the poverenikUsername property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPoverenikUsername(String value) {
            this.poverenikUsername = value;
        }

        /**
         * Gets the value of the razlog property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRazlog() {
            return razlog;
        }

        /**
         * Sets the value of the razlog property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRazlog(String value) {
            this.razlog = value;
        }

    }

}
