//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.20 at 01:14:13 PM CET 
//


package com.xml.organvlasti.model.silenceAppeal;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.projekat.zalbazbogcutanja package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.projekat.zalbazbogcutanja
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ZalbaCutanje }
     * 
     */
    public ZalbaCutanje createZalbaCutanje() {
        return new ZalbaCutanje();
    }

    /**
     * Create an instance of {@link Trazlozi }
     * 
     */
    public Trazlozi createTrazlozi() {
        return new Trazlozi();
    }

    /**
     * Create an instance of {@link TmestoDatum }
     * 
     */
    public TmestoDatum createTmestoDatum() {
        return new TmestoDatum();
    }

    /**
     * Create an instance of {@link TFizickoLice }
     * 
     */
    public TFizickoLice createTFizickoLice() {
        return new TFizickoLice();
    }

    /**
     * Create an instance of {@link TteloZalbe }
     * 
     */
    public TteloZalbe createTteloZalbe() {
        return new TteloZalbe();
    }

    /**
     * Create an instance of {@link ZalbaCutanje.ZalbaStatus }
     * 
     */
    public ZalbaCutanje.ZalbaStatus createZalbaCutanjeZalbaStatus() {
        return new ZalbaCutanje.ZalbaStatus();
    }

    /**
     * Create an instance of {@link ZalbaCutanje.ZalbaBroj }
     * 
     */
    public ZalbaCutanje.ZalbaBroj createZalbaCutanjeZalbaBroj() {
        return new ZalbaCutanje.ZalbaBroj();
    }

    /**
     * Create an instance of {@link TPravnoLice }
     * 
     */
    public TPravnoLice createTPravnoLice() {
        return new TPravnoLice();
    }

    /**
     * Create an instance of {@link Adresa }
     * 
     */
    public Adresa createAdresa() {
        return new Adresa();
    }

    /**
     * Create an instance of {@link TZakon }
     * 
     */
    public TZakon createTZakon() {
        return new TZakon();
    }

    /**
     * Create an instance of {@link Trazlozi.Razlog }
     * 
     */
    public Trazlozi.Razlog createTrazloziRazlog() {
        return new Trazlozi.Razlog();
    }

    /**
     * Create an instance of {@link TmestoDatum.Mesto }
     * 
     */
    public TmestoDatum.Mesto createTmestoDatumMesto() {
        return new TmestoDatum.Mesto();
    }

    /**
     * Create an instance of {@link TmestoDatum.Datum }
     * 
     */
    public TmestoDatum.Datum createTmestoDatumDatum() {
        return new TmestoDatum.Datum();
    }

    /**
     * Create an instance of {@link TFizickoLice.Ime }
     * 
     */
    public TFizickoLice.Ime createTFizickoLiceIme() {
        return new TFizickoLice.Ime();
    }

    /**
     * Create an instance of {@link TFizickoLice.Prezime }
     * 
     */
    public TFizickoLice.Prezime createTFizickoLicePrezime() {
        return new TFizickoLice.Prezime();
    }

    /**
     * Create an instance of {@link TteloZalbe.NazivOrgana }
     * 
     */
    public TteloZalbe.NazivOrgana createTteloZalbeNazivOrgana() {
        return new TteloZalbe.NazivOrgana();
    }

}
