//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.20 at 01:14:13 PM CET 
//


package com.xml.organvlasti.model.silenceAppeal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for Ttelo_zalbe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ttelo_zalbe">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zakon" type="{http://www.projekat.org/zalbazbogcutanja}TZakon" minOccurs="0"/>
 *         &lt;element name="naziv_organa" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="razlozi" type="{http://www.projekat.org/zalbazbogcutanja}Trazlozi" minOccurs="0"/>
 *         &lt;element name="datum" type="{http://www.projekat.org/zalbazbogcutanja}TDatum" minOccurs="0"/>
 *         &lt;element name="podaci_o_zahtevu_i_informaciji" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="1000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="napomena" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ttelo_zalbe", propOrder = {
    "zakon",
    "nazivOrgana",
    "razlozi",
    "datum",
    "podaciOZahtevuIInformaciji",
    "napomena"
})
public class TteloZalbe {

    protected TZakon zakon;
    @XmlElement(name = "naziv_organa")
    protected TteloZalbe.NazivOrgana nazivOrgana;
    protected Trazlozi razlozi;
    protected String datum;
    @XmlElement(name = "podaci_o_zahtevu_i_informaciji")
    protected String podaciOZahtevuIInformaciji;
    protected String napomena;

    /**
     * Gets the value of the zakon property.
     * 
     * @return
     *     possible object is
     *     {@link TZakon }
     *     
     */
    public TZakon getZakon() {
        return zakon;
    }

    /**
     * Sets the value of the zakon property.
     * 
     * @param value
     *     allowed object is
     *     {@link TZakon }
     *     
     */
    public void setZakon(TZakon value) {
        this.zakon = value;
    }

    /**
     * Gets the value of the nazivOrgana property.
     * 
     * @return
     *     possible object is
     *     {@link TteloZalbe.NazivOrgana }
     *     
     */
    public TteloZalbe.NazivOrgana getNazivOrgana() {
        return nazivOrgana;
    }

    /**
     * Sets the value of the nazivOrgana property.
     * 
     * @param value
     *     allowed object is
     *     {@link TteloZalbe.NazivOrgana }
     *     
     */
    public void setNazivOrgana(TteloZalbe.NazivOrgana value) {
        this.nazivOrgana = value;
    }

    /**
     * Gets the value of the razlozi property.
     * 
     * @return
     *     possible object is
     *     {@link Trazlozi }
     *     
     */
    public Trazlozi getRazlozi() {
        return razlozi;
    }

    /**
     * Sets the value of the razlozi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Trazlozi }
     *     
     */
    public void setRazlozi(Trazlozi value) {
        this.razlozi = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }

    /**
     * Gets the value of the podaciOZahtevuIInformaciji property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPodaciOZahtevuIInformaciji() {
        return podaciOZahtevuIInformaciji;
    }

    /**
     * Sets the value of the podaciOZahtevuIInformaciji property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPodaciOZahtevuIInformaciji(String value) {
        this.podaciOZahtevuIInformaciji = value;
    }

    /**
     * Gets the value of the napomena property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNapomena() {
        return napomena;
    }

    /**
     * Sets the value of the napomena property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNapomena(String value) {
        this.napomena = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class NazivOrgana {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "property", required = true)
        protected String property;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

    }

}
