//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.20 at 01:14:13 PM CET 
//


package com.xml.organvlasti.model.silenceAppeal;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zalba_status" form="qualified">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="zalba_broj">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.projekat.org/zalbazbogcutanja>TBroj">
 *                 &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="naslov" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="podaci_o_povereniku" type="{http://www.projekat.org/zalbazbogcutanja}TPravno_lice" minOccurs="0"/>
 *         &lt;element name="telo_zalbe" type="{http://www.projekat.org/zalbazbogcutanja}Ttelo_zalbe"/>
 *         &lt;element name="podaci_o_podnosiocu_zalbe" type="{http://www.projekat.org/zalbazbogcutanja}TFizicko_lice"/>
 *         &lt;element name="podaci_o_mestu_i_datumu_podnosenja_zalbe" type="{http://www.projekat.org/zalbazbogcutanja}Tmesto_datum"/>
 *       &lt;/sequence>
 *       &lt;attribute name="username" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="nazivOrgana" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;minLength value="1"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="broj" use="required" type="{http://www.projekat.org/zalbazbogcutanja}TBroj" />
 *       &lt;attribute name="about" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="status" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="poverenikUsername" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zalbaStatus",
    "zalbaBroj",
    "naslov",
    "podaciOPovereniku",
    "teloZalbe",
    "podaciOPodnosiocuZalbe",
    "podaciOMestuIDatumuPodnosenjaZalbe"
})
@XmlRootElement(name = "zalba_cutanje")
public class ZalbaCutanje {

    @XmlElement(name = "zalba_status", required = true)
    protected ZalbaCutanje.ZalbaStatus zalbaStatus;
    @XmlElement(name = "zalba_broj", required = true)
    protected ZalbaCutanje.ZalbaBroj zalbaBroj;
    protected String naslov;
    @XmlElement(name = "podaci_o_povereniku")
    protected TPravnoLice podaciOPovereniku;
    @XmlElement(name = "telo_zalbe", required = true)
    protected TteloZalbe teloZalbe;
    @XmlElement(name = "podaci_o_podnosiocu_zalbe", required = true)
    protected TFizickoLice podaciOPodnosiocuZalbe;
    @XmlElement(name = "podaci_o_mestu_i_datumu_podnosenja_zalbe", required = true)
    protected TmestoDatum podaciOMestuIDatumuPodnosenjaZalbe;
    @XmlAttribute(name = "username", required = true)
    protected String username;
    @XmlAttribute(name = "nazivOrgana", required = true)
    protected String nazivOrgana;
    @XmlAttribute(name = "broj", required = true)
    protected String broj;
    @XmlAttribute(name = "about")
    protected String about;
    @XmlAttribute(name = "status", required = true)
    protected String status;
    @XmlAttribute(name = "poverenikUsername", required = true)
    protected String poverenikUsername;

    /**
     * Gets the value of the zalbaStatus property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbaCutanje.ZalbaStatus }
     *     
     */
    public ZalbaCutanje.ZalbaStatus getZalbaStatus() {
        return zalbaStatus;
    }

    /**
     * Sets the value of the zalbaStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbaCutanje.ZalbaStatus }
     *     
     */
    public void setZalbaStatus(ZalbaCutanje.ZalbaStatus value) {
        this.zalbaStatus = value;
    }

    /**
     * Gets the value of the zalbaBroj property.
     * 
     * @return
     *     possible object is
     *     {@link ZalbaCutanje.ZalbaBroj }
     *     
     */
    public ZalbaCutanje.ZalbaBroj getZalbaBroj() {
        return zalbaBroj;
    }

    /**
     * Sets the value of the zalbaBroj property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZalbaCutanje.ZalbaBroj }
     *     
     */
    public void setZalbaBroj(ZalbaCutanje.ZalbaBroj value) {
        this.zalbaBroj = value;
    }

    /**
     * Gets the value of the naslov property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNaslov() {
        return naslov;
    }

    /**
     * Sets the value of the naslov property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNaslov(String value) {
        this.naslov = value;
    }

    /**
     * Gets the value of the podaciOPovereniku property.
     * 
     * @return
     *     possible object is
     *     {@link TPravnoLice }
     *     
     */
    public TPravnoLice getPodaciOPovereniku() {
        return podaciOPovereniku;
    }

    /**
     * Sets the value of the podaciOPovereniku property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPravnoLice }
     *     
     */
    public void setPodaciOPovereniku(TPravnoLice value) {
        this.podaciOPovereniku = value;
    }

    /**
     * Gets the value of the teloZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link TteloZalbe }
     *     
     */
    public TteloZalbe getTeloZalbe() {
        return teloZalbe;
    }

    /**
     * Sets the value of the teloZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link TteloZalbe }
     *     
     */
    public void setTeloZalbe(TteloZalbe value) {
        this.teloZalbe = value;
    }

    /**
     * Gets the value of the podaciOPodnosiocuZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link TFizickoLice }
     *     
     */
    public TFizickoLice getPodaciOPodnosiocuZalbe() {
        return podaciOPodnosiocuZalbe;
    }

    /**
     * Sets the value of the podaciOPodnosiocuZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link TFizickoLice }
     *     
     */
    public void setPodaciOPodnosiocuZalbe(TFizickoLice value) {
        this.podaciOPodnosiocuZalbe = value;
    }

    /**
     * Gets the value of the podaciOMestuIDatumuPodnosenjaZalbe property.
     * 
     * @return
     *     possible object is
     *     {@link TmestoDatum }
     *     
     */
    public TmestoDatum getPodaciOMestuIDatumuPodnosenjaZalbe() {
        return podaciOMestuIDatumuPodnosenjaZalbe;
    }

    /**
     * Sets the value of the podaciOMestuIDatumuPodnosenjaZalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link TmestoDatum }
     *     
     */
    public void setPodaciOMestuIDatumuPodnosenjaZalbe(TmestoDatum value) {
        this.podaciOMestuIDatumuPodnosenjaZalbe = value;
    }

    /**
     * Gets the value of the username property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUsername() {
        return username;
    }

    /**
     * Sets the value of the username property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUsername(String value) {
        this.username = value;
    }

    /**
     * Gets the value of the nazivOrgana property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNazivOrgana() {
        return nazivOrgana;
    }

    /**
     * Sets the value of the nazivOrgana property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNazivOrgana(String value) {
        this.nazivOrgana = value;
    }

    /**
     * Gets the value of the broj property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBroj() {
        return broj;
    }

    /**
     * Sets the value of the broj property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBroj(String value) {
        this.broj = value;
    }

    /**
     * Gets the value of the about property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAbout() {
        return about;
    }

    /**
     * Sets the value of the about property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAbout(String value) {
        this.about = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatus(String value) {
        this.status = value;
    }

    /**
     * Gets the value of the poverenikUsername property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPoverenikUsername() {
        return poverenikUsername;
    }

    /**
     * Sets the value of the poverenikUsername property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPoverenikUsername(String value) {
        this.poverenikUsername = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.projekat.org/zalbazbogcutanja>TBroj">
     *       &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ZalbaBroj {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "property", required = true)
        protected String property;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="property" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ZalbaStatus {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "property", required = true)
        protected String property;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the property property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getProperty() {
            return property;
        }

        /**
         * Sets the value of the property property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setProperty(String value) {
            this.property = value;
        }

    }

}
