//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-1 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.01.31 at 05:07:52 PM CET 
//


package com.xml.project.model.report;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zahtevi">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="brojPodnetih" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="brojUsvojenih" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="brojOdbacenih" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="brojOdbijenih" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="zalbe">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="brojPodnetih" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="brojZbogNepostupanja" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="brojZbogOdbijanja" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="brojNaZakljucakOdbacivanju" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="datum" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zahtevi",
    "zalbe"
})
@XmlRootElement(name = "izvestaj")
public class Izvestaj {

    @XmlElement(required = true)
    protected Izvestaj.Zahtevi zahtevi;
    @XmlElement(required = true)
    protected Izvestaj.Zalbe zalbe;
    @XmlAttribute(name = "id")
    protected String id;
    @XmlAttribute(name = "datum")
    protected String datum;
    @XmlAttribute(name = "user")
    protected String user;
    
    public Izvestaj() {}
    
    
	@Override
	public String toString() {
		return "Izvestaj [zahtevi=" + zahtevi + ", zalbe=" + zalbe + ", id=" + id + ", datum=" + datum + ", user="
				+ user + "]";
	}

	public String getUser() {
		return user;
	}


	public void setUser(String user) {
		this.user = user;
	}


	/**
     * Gets the value of the zahtevi property.
     * 
     * @return
     *     possible object is
     *     {@link Izvestaj.Zahtevi }
     *     
     */
    public Izvestaj.Zahtevi getZahtevi() {
        return zahtevi;
    }

    /**
     * Sets the value of the zahtevi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Izvestaj.Zahtevi }
     *     
     */
    public void setZahtevi(Izvestaj.Zahtevi value) {
        this.zahtevi = value;
    }

    /**
     * Gets the value of the zalbe property.
     * 
     * @return
     *     possible object is
     *     {@link Izvestaj.Zalbe }
     *     
     */
    public Izvestaj.Zalbe getZalbe() {
        return zalbe;
    }

    /**
     * Sets the value of the zalbe property.
     * 
     * @param value
     *     allowed object is
     *     {@link Izvestaj.Zalbe }
     *     
     */
    public void setZalbe(Izvestaj.Zalbe value) {
        this.zalbe = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the datum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDatum() {
        return datum;
    }

    /**
     * Sets the value of the datum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDatum(String value) {
        this.datum = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="brojPodnetih" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="brojUsvojenih" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="brojOdbacenih" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="brojOdbijenih" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojPodnetih",
        "brojUsvojenih",
        "brojOdbacenih",
        "brojOdbijenih"
    })
    public static class Zahtevi {

        protected int brojPodnetih;
        protected int brojUsvojenih;
        protected int brojOdbacenih;
        protected int brojOdbijenih;

        public Zahtevi() {}
        
        @Override
		public String toString() {
			return "Zahtevi [brojPodnetih=" + brojPodnetih + ", brojUsvojenih=" + brojUsvojenih + ", brojOdbacenih="
					+ brojOdbacenih + ", brojOdbijenih=" + brojOdbijenih + "]";
		}

		/**
         * Gets the value of the brojPodnetih property.
         * 
         */
        public int getBrojPodnetih() {
            return brojPodnetih;
        }

        /**
         * Sets the value of the brojPodnetih property.
         * 
         */
        public void setBrojPodnetih(int value) {
            this.brojPodnetih = value;
        }

        /**
         * Gets the value of the brojUsvojenih property.
         * 
         */
        public int getBrojUsvojenih() {
            return brojUsvojenih;
        }

        /**
         * Sets the value of the brojUsvojenih property.
         * 
         */
        public void setBrojUsvojenih(int value) {
            this.brojUsvojenih = value;
        }

        /**
         * Gets the value of the brojOdbacenih property.
         * 
         */
        public int getBrojOdbacenih() {
            return brojOdbacenih;
        }

        /**
         * Sets the value of the brojOdbacenih property.
         * 
         */
        public void setBrojOdbacenih(int value) {
            this.brojOdbacenih = value;
        }

        /**
         * Gets the value of the brojOdbijenih property.
         * 
         */
        public int getBrojOdbijenih() {
            return brojOdbijenih;
        }

        /**
         * Sets the value of the brojOdbijenih property.
         * 
         */
        public void setBrojOdbijenih(int value) {
            this.brojOdbijenih = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="brojPodnetih" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="brojZbogNepostupanja" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="brojZbogOdbijanja" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="brojNaZakljucakOdbacivanju" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "brojPodnetih",
        "brojZbogNepostupanja",
        "brojZbogOdbijanja",
        "brojNaZakljucakOdbacivanju"
    })
    public static class Zalbe {

        protected int brojPodnetih;
        protected int brojZbogNepostupanja;
        protected int brojZbogOdbijanja;
        protected int brojNaZakljucakOdbacivanju;

        public Zalbe() {}
        
        @Override
		public String toString() {
			return "Zalbe [brojPodnetih=" + brojPodnetih + ", brojZbogNepostupanja=" + brojZbogNepostupanja
					+ ", brojZbogOdbijanja=" + brojZbogOdbijanja + ", brojNaZakljucakOdbacivanju="
					+ brojNaZakljucakOdbacivanju + "]";
		}

		/**
         * Gets the value of the brojPodnetih property.
         * 
         */
        public int getBrojPodnetih() {
            return brojPodnetih;
        }

        /**
         * Sets the value of the brojPodnetih property.
         * 
         */
        public void setBrojPodnetih(int value) {
            this.brojPodnetih = value;
        }

        /**
         * Gets the value of the brojZbogNepostupanja property.
         * 
         */
        public int getBrojZbogNepostupanja() {
            return brojZbogNepostupanja;
        }

        /**
         * Sets the value of the brojZbogNepostupanja property.
         * 
         */
        public void setBrojZbogNepostupanja(int value) {
            this.brojZbogNepostupanja = value;
        }

        /**
         * Gets the value of the brojZbogOdbijanja property.
         * 
         */
        public int getBrojZbogOdbijanja() {
            return brojZbogOdbijanja;
        }

        /**
         * Sets the value of the brojZbogOdbijanja property.
         * 
         */
        public void setBrojZbogOdbijanja(int value) {
            this.brojZbogOdbijanja = value;
        }

        /**
         * Gets the value of the brojNaZakljucakOdbacivanju property.
         * 
         */
        public int getBrojNaZakljucakOdbacivanju() {
            return brojNaZakljucakOdbacivanju;
        }

        /**
         * Sets the value of the brojNaZakljucakOdbacivanju property.
         * 
         */
        public void setBrojNaZakljucakOdbacivanju(int value) {
            this.brojNaZakljucakOdbacivanju = value;
        }

    }

}
